### ISSUE TITLE
plugins access a class or variable in the main program

### ISSUE THREAD

**Issue by mgh67** [VgTajdd/plugin_manager#2]
First of all, I would like to thank you for plugin manager , IT IS VERY GOOD.
I had a question about it.

How can plugins access a class or variable in the main body of the program and can get a value or call the class or function.

please show me in a example code.

thank

**Comment by VgTajdd** [comment]
Hi @mgh67,

This plugin manager expects a dynamic library with the entry point specified here:

https://github.com/VgTajdd/plugin_manager/blob/8cbeefdaf04eeebfae4beb6d7969f723383b97b0/lib/common/include/common/PluginDefines.h#L14-L24

and I think the code-snippet you need it's something more generic, so, you could follow this code as an example:

https://github.com/VgTajdd/plugin_manager/blob/8cbeefdaf04eeebfae4beb6d7969f723383b97b0/lib/plugin_manager/src/PluginManager.cpp#L43-L59

Hope it helps,

Best,
Agustin

**Comment by dakob-com** [comment]
I am sorry
I dont understand very well
I am beginner c++.
If you can show me in sample code.
I want access my plugin to special classes or ... in main program code.
